stages:
  measure:
    cmd: jupytext --sync --exec AlgoMetrics.py
    deps:
    - AlgoMetrics.py
    - runs/0.9/metrics.csv
    - runs/0.10/metrics.csv
    - runs/0.11/metrics.csv
    - runs/0.12/metrics.csv
    - runs/0.13/metrics.csv
    - runs/0.14/metrics.csv
    - runs/main/metrics.csv
    outs:
    - AlgoMetrics.ipynb:
        cache: false

  render:
    cmd: jupyter nbconvert --to html AlgoMetrics.ipynb
    deps:
    - AlgoMetrics.ipynb
    outs:
    - AlgoMetrics.html
