# Define root environment for managing LensKit
name: lkpm
channels:
- conda-forge
dependencies:
- python=3.10
- pip
- pandas=1
- flake8
- scipy
- numba
- seaborn
- notebook
- jupytext
- ipython
- docopt
- dvc>=3
- tcllib
- lenskit>=0.14
platforms:
- osx-64
- osx-arm64
- linux-64
