name: lkpm
channels:
- conda-forge
dependencies:
- python=3.8
- pip
- psutil
- pandas<1.0
- scipy
- numba=<0.50
- cffi
- pyarrow
- tbb
- seaborn
- notebook
- jupytext
- ipython
- ipywidgets
- tqdm
- statsmodels
- docopt
- dvc>=2.3
- dvc-s3>=2.3
- papermill
- pip:
  - lenskit@git+https://github.com/lenskit/lkpy
