# Define root environment for managing LensKit
name: lkpm
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - invoke
  - jsonnet
  - pandas=2
  - pyarrow
  - scipy
  - numba
  - seaborn
  - notebook
  - jupytext
  - ipython
  - docopt
  - dvc>=3.50,<4
  - dvc-http
  - dvc-s3
  - dvc-webdav
  - ruff
  - lenskit>=0.14,<2024
platforms:
  - osx-arm64
  - linux-64
