name: lkpm
channels:
- conda-forge
dependencies:
- python=3.9
- conda-lock>=0.13.2
- pip
- psutil
- pandas
- libblas=*=*mkl
- scipy
- numba
- cffi>=1.12
- pyarrow=4
- tbb=2020
- mkl=2020
- seaborn
- notebook
- jupytext
- ipython
- docopt
- dvc>=2.6
- dvc-s3>=2.6
- python-gist
- pip:
  - lenskit@git+https://github.com/lenskit/lkpy
