# Define root environment for managing LensKit
name: lkpm
channels:
- conda-forge
dependencies:
- python=3.9
- pip
- mamba
- pandas
- flake8
- scipy
- numba
- seaborn
- notebook
- jupytext
- ipython
- docopt
- dvc>=2.6
- dvc-s3>=2.6
- python-gist
- lenskit>=0.13
