name: lkpm
channels:
- conda-forge
dependencies:
- python=3.8
- pip
- psutil
- pandas
- libblas=*=*mkl
- scipy
- numba
- cffi
- pyarrow
- tbb=2020
- mkl=2020
- seaborn
- notebook
- jupytext
- ipython
- statsmodels
- docopt
- dvc>=2.3
- dvc-s3>=2.3
- papermill
- pip:
  - lenskit@git+https://github.com/lenskit/lkpy
