# Define root environment for managing LensKit
name: lkpm
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - invoke=2
  - jsonnet
  - ruamel.yaml
  - pandas=2
  - pyarrow>=14
  - scipy=1
  - seaborn
  - notebook>=7
  - jupytext=1
  - ipython>=7
  - docopt>=0.6
  - dvc>=3.50,<4
  - dvc-http
  - dvc-s3
  - dvc-webdav
  - micromamba
  - ruff
  - lenskit>=0.14,<2024
  - pip:
      - sandal>=0.1.0a5
platforms:
  - osx-arm64
  - linux-64
