[project]
name = 'lk-perf-monitor'
platforms = ['linux-64', 'osx-arm64']
channels = ['conda-forge']

[dependencies]
python = "~=3.11.0"
invoke = "~=2.0"
jsonnet = "*"
"ruamel.yaml" = "*"
pandas = "~=2.0"
pyarrow = ">=14"
scipy = "~=1.0"
seaborn = "*"
notebook = ">=7"
jupytext = "~=1.0"
ipython = ">=7"
docopt = ">=0.6"
dvc = ">=3.50,<4"
dvc-http = "*"
dvc-s3 = "*"
dvc-webdav = "*"
ruff = "*"
lenskit = ">=0.14,<2024"

[pypi-dependencies]
sandal = { git = "https://github.com/mdekstrand/sandal" }

[feature.lk09]
platforms = ["linux-64"]

[feature.lk09.dependencies]
python = "~=3.7.0"
pandas = "0.24"
numpy = "1.17"
pyarrow = "~=4.0"
scipy = "*"
numba = "<0.50"
cffi = "*"
libblas = { build = "*mkl*" }
tbb = "~=2020.0"
mkl = "~=2020.0"
docopt = "*"
binpickle = "=0.3.3"
joblib = "0.15"

[feature.lk09.pypi-dependencies]
lenskit = "~=0.9.0"

[feature.lk10]
platforms = ["linux-64"]

[feature.lk10.dependencies]
python = "~=3.7.0"
pandas = "~=1.0.0"
numpy = "~=1.17.0"
pyarrow = "~=4.0"
scipy = "*"
numba = "<0.51"
cffi = "*"
libblas = { build = "*mkl*" }
tbb = "~=2020.0"
mkl = "~=2020.0"
docopt = "*"
binpickle = "=0.3.3"

[feature.lk10.pypi-dependencies]
lenskit = "~=0.10.1"

[feature.lk11]
platforms = ["linux-64"]

[feature.lk11.dependencies]
python = "~=3.7.0"
pyarrow = "~=4.0"
libblas = { build = "*mkl*" }
tbb = "~=2020.0"
mkl = "~=2020.0"
docopt = "*"
lenskit = "~=0.11.0"

[feature.lk12]
platforms = ["linux-64"]

[feature.lk12.dependencies]
python = "~=3.8.0"
pyarrow = "~=4.0"
libblas = { build = "*mkl*" }
tbb = "~=2020.0"
mkl = "~=2020.0"
docopt = "*"
lenskit = "~=0.12.0"

[feature.lk13]
platforms = ["linux-64"]

[feature.lk13.dependencies]
python = "~=3.8.0"
pyarrow = "~=4.0"
libblas = { build = "*mkl*" }
tbb = "~=2020.0"
mkl = "~=2020.0"
docopt = "*"
implicit = "~=0.4.0"
lenskit = "~=0.13.0"

[feature.lk14]
platforms = ["linux-64"]

[feature.lk14.dependencies]
python = "~=3.10.0"
pyarrow = "*"
libblas = { build = "*mkl*" }
tbb = "*"
docopt = "*"
numpy = "~=1.23.0"
numba = ">=0.56,<0.57"
implicit = "~=0.7.0"
lenskit = "~=0.14.0"

[feature.lk14.pypi-dependencies]
sandal = { git = "https://github.com/mdekstrand/sandal" }
lenskit-implicit = { git = "https://github.com/lenskit/lenskit-implicit" }

[feature.lk-main]
platforms = ["linux-64"]

[feature.lk-main.dependencies]
python = "~=3.12.0"
psutil = "*"
pyarrow = ">=16"
docopt = "*"
pyzmq = "*"
msgpack-python = "*"
threadpoolctl = "*"
numba = ">=0.58"
implicit = "~=0.7.0"

[feature.lk-main.pypi-dependencies]
sandal = { git = "https://github.com/mdekstrand/sandal" }
lenskit = { git = "https://github.com/lenskit/lkpy", subdirectory="lenskit" }
lenskit-funksvd = { git = "https://github.com/lenskit/lkpy", subdirectory="lenskit-funkvsd" }
lenskit-implicit = { git = "https://github.com/lenskit/lkpy", subdirectory="lenskit-implicit" }

[environments]
lk09 = { features = ["lk09"], no-default-feature = true }
lk10 = { features = ["lk10"], no-default-feature = true }
lk11 = { features = ["lk11"], no-default-feature = true }
lk12 = { features = ["lk12"], no-default-feature = true }
lk13 = { features = ["lk13"], no-default-feature = true }
lk14 = { features = ["lk14"], no-default-feature = true }
lk-main = { features = ["lk-main"], no-default-feature = true }
