[project]
name = 'lk-perf-monitor'
platforms = ['linux-64', 'osx-arm64']
channels = ['conda-forge']

[dependencies]
python = "=3.11"
invoke = "~=2.0"
jsonnet = "*"
"ruamel.yaml" = "*"
pandas = "~=2.0"
pyarrow = ">=14"
scipy = "~=1.0"
seaborn = "*"
notebook = ">=7"
jupytext = "~=1.0"
ipython = ">=7"
docopt = ">=0.6"
dvc = ">=3.50,<4"
dvc-http = "*"
dvc-s3 = "*"
dvc-webdav = "*"
ruff = "*"
lenskit = ">=0.14,<2024"

[pypi-dependencies]
sandal = { git = "https://github.com/mdekstrand/sandal" }

[feature.lk09]
platforms = ["linux-64"]

[feature.lk09.dependencies]
python = "3.7"
pandas = "0.24"
numpy = "1.17"
pyarrow = "4"
scipy = "*"
numba = "<0.50"
cffi = "*"
libblas = { build = "*mkl*" }
tbb = "2020"
mkl = "2020"
docopt = "*"
binpickle = "*"
joblib = "0.15"

[feature.lk09.pypi-dependencies]
lenskit = "~=0.9.0"

[environments]
lk09 = { features = ["lk09"], no-default-feature = true }
