[tool.coverage.run]
# relative_files = true

[tool.ruff]
line-length = 100
target-version = "py37"
exclude = [".git", "__pycache__", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F", "I"]
unfixable = ["F401"]

[tool.ruff.lint.per-file-ignores]
# Importing PyTest fixtures triggers F811
"*/tests/*.py" = ["F811"]

[tool.ruff.lint.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "testing",
  "first-party",
  "local-folder",
]
known-first-party = ["lenskit"]

[tool.ruff.lint.isort.sections]
testing = ["pytest", "hypothesis"]

[tool.pyright]
typeCheckingMode = "basic"
exclude = ["docs/*", ".pixi/*"]
reportMissingImports = true
reportMissingTypeStubs = false
