stages:
  als:
    foreach:
    - ml10m
    do:
      cmd: python run-algo.py --splits data-split/${item} -o runs/${item}-ALS -M runs/${item}-ALS.json ALS
      wdir: ..
      deps:
      - run-algo.py
      - lkdemo/algorithms.py
      - data-split/${item}
      outs:
      - runs/${item}-ALS
      metrics:
      - runs/${item}-ALS.json
