stages:
  als:
    foreach:
    - ml100k
    - ml1m
    - ml10m
    - ml20m
    do:
      cmd: python run-algo.py --splits data-split/${item} -o runs/${item}-ALS -M runs/${item}-ALS.json ALS
      wdir: ..
      deps:
      - run-algo.py
      - lkdemo/algorithms.py
      - data-split/${item}
      outs:
      - runs/${item}-ALS
      metrics:
      - runs/${item}-ALS.json
      params:
      - lenskit.version

  item-item:
    foreach:
    - ml100k
    - ml1m
    - ml10m
    - ml20m
    do:
      cmd: python run-algo.py --splits data-split/${item} -o runs/${item}-II -M runs/${item}-II.json II
      wdir: ..
      deps:
      - run-algo.py
      - lkdemo/algorithms.py
      - data-split/${item}
      outs:
      - runs/${item}-II
      metrics:
      - runs/${item}-II.json
      params:
      - lenskit.version

  user-user:
    foreach:
    - ml100k
    - ml1m
    - ml10m
    do:
      cmd: python run-algo.py --splits data-split/${item} -o runs/${item}-UU -M runs/${item}-UU.json UU
      wdir: ..
      deps:
      - run-algo.py
      - lkdemo/algorithms.py
      - data-split/${item}
      outs:
      - runs/${item}-UU
      metrics:
      - runs/${item}-UU.json
      params:
      - lenskit.version
