stages:
  ml100k:
    cmd: python split-data.py ml100k -o data-split/ml100k
    wdir: ..
    deps:
    - split-data.py
    - data/ml-100k
    outs:
    - data-split/ml100k
  
  ml1m:
    cmd: python split-data.py ml1m -o data-split/ml1m
    wdir: ..
    deps:
    - split-data.py
    - data/ml-1m
    outs:
    - data-split/ml1m

  ml10m:
    cmd: python split-data.py ml10m -o data-split/ml10m
    wdir: ..
    deps:
    - split-data.py
    - data/ml-10M100K
    outs:
    - data-split/ml10m

  ml20m:
    cmd: python split-data.py ml20m -o data-split/ml20m
    wdir: ..
    deps:
    - split-data.py
    - data/ml-20m
    outs:
    - data-split/ml20m
