stages:
  collect:
    cmd: python collect-metrics.py -o runs/0.13/metrics.csv runs/0.13
    deps:
    - collect-metrics.py
    - runs/0.13/ml100k-II.json
    - runs/0.13/ml100k-UU.json
    - runs/0.13/ml100k-ALS.json
    - runs/0.13/ml100k-IALS.json
    - runs/0.13/ml100k-implicit.json
    - runs/0.13/ml1m-II.json
    - runs/0.13/ml1m-UU.json
    - runs/0.13/ml1m-ALS.json
    - runs/0.13/ml1m-IALS.json
    - runs/0.13/ml1m-implicit.json
    - runs/0.13/ml10m-II.json
    - runs/0.13/ml10m-UU.json
    - runs/0.13/ml10m-ALS.json
    - runs/0.13/ml10m-IALS.json
    - runs/0.13/ml10m-implicit.json
    - runs/0.13/ml20m-II.json
    - runs/0.13/ml20m-ALS.json
    - runs/0.13/ml20m-IALS.json
    - runs/0.13/ml20m-implicit.json
    outs:
    - runs/0.13/metrics.csv
    wdir: ../..
  ml100k-ALS:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml100k -o runs/0.13/ml100k-ALS
      -M runs/0.13/ml100k-ALS.json ALS
    deps:
    - data-split/ml100k
    outs:
    - runs/0.13/ml100k-ALS
    - runs/0.13/ml100k-ALS.json
    wdir: ../..
  ml100k-IALS:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml100k -o runs/0.13/ml100k-IALS
      -M runs/0.13/ml100k-IALS.json IALS
    deps:
    - data-split/ml100k
    outs:
    - runs/0.13/ml100k-IALS
    - runs/0.13/ml100k-IALS.json
    wdir: ../..
  ml100k-II:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml100k -o runs/0.13/ml100k-II
      -M runs/0.13/ml100k-II.json II
    deps:
    - data-split/ml100k
    outs:
    - runs/0.13/ml100k-II
    - runs/0.13/ml100k-II.json
    wdir: ../..
  ml100k-UU:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml100k -o runs/0.13/ml100k-UU
      -M runs/0.13/ml100k-UU.json UU
    deps:
    - data-split/ml100k
    outs:
    - runs/0.13/ml100k-UU
    - runs/0.13/ml100k-UU.json
    wdir: ../..
  ml100k-implicit:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml100k -o runs/0.13/ml100k-implicit
      -M runs/0.13/ml100k-implicit.json implicit
    deps:
    - data-split/ml100k
    outs:
    - runs/0.13/ml100k-implicit
    - runs/0.13/ml100k-implicit.json
    wdir: ../..
  ml10m-ALS:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml10m -o runs/0.13/ml10m-ALS
      -M runs/0.13/ml10m-ALS.json ALS
    deps:
    - data-split/ml10m
    outs:
    - runs/0.13/ml10m-ALS
    - runs/0.13/ml10m-ALS.json
    wdir: ../..
  ml10m-IALS:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml10m -o runs/0.13/ml10m-IALS
      -M runs/0.13/ml10m-IALS.json IALS
    deps:
    - data-split/ml10m
    outs:
    - runs/0.13/ml10m-IALS
    - runs/0.13/ml10m-IALS.json
    wdir: ../..
  ml10m-II:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml10m -o runs/0.13/ml10m-II
      -M runs/0.13/ml10m-II.json II
    deps:
    - data-split/ml10m
    outs:
    - runs/0.13/ml10m-II
    - runs/0.13/ml10m-II.json
    wdir: ../..
  ml10m-UU:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml10m -o runs/0.13/ml10m-UU
      -M runs/0.13/ml10m-UU.json UU
    deps:
    - data-split/ml10m
    outs:
    - runs/0.13/ml10m-UU
    - runs/0.13/ml10m-UU.json
    wdir: ../..
  ml10m-implicit:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml10m -o runs/0.13/ml10m-implicit
      -M runs/0.13/ml10m-implicit.json implicit
    deps:
    - data-split/ml10m
    outs:
    - runs/0.13/ml10m-implicit
    - runs/0.13/ml10m-implicit.json
    wdir: ../..
  ml1m-ALS:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml1m -o runs/0.13/ml1m-ALS
      -M runs/0.13/ml1m-ALS.json ALS
    deps:
    - data-split/ml1m
    outs:
    - runs/0.13/ml1m-ALS
    - runs/0.13/ml1m-ALS.json
    wdir: ../..
  ml1m-IALS:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml1m -o runs/0.13/ml1m-IALS
      -M runs/0.13/ml1m-IALS.json IALS
    deps:
    - data-split/ml1m
    outs:
    - runs/0.13/ml1m-IALS
    - runs/0.13/ml1m-IALS.json
    wdir: ../..
  ml1m-II:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml1m -o runs/0.13/ml1m-II
      -M runs/0.13/ml1m-II.json II
    deps:
    - data-split/ml1m
    outs:
    - runs/0.13/ml1m-II
    - runs/0.13/ml1m-II.json
    wdir: ../..
  ml1m-UU:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml1m -o runs/0.13/ml1m-UU
      -M runs/0.13/ml1m-UU.json UU
    deps:
    - data-split/ml1m
    outs:
    - runs/0.13/ml1m-UU
    - runs/0.13/ml1m-UU.json
    wdir: ../..
  ml1m-implicit:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml1m -o runs/0.13/ml1m-implicit
      -M runs/0.13/ml1m-implicit.json implicit
    deps:
    - data-split/ml1m
    outs:
    - runs/0.13/ml1m-implicit
    - runs/0.13/ml1m-implicit.json
    wdir: ../..
  ml20m-ALS:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml20m -o runs/0.13/ml20m-ALS
      -M runs/0.13/ml20m-ALS.json ALS
    deps:
    - data-split/ml20m
    outs:
    - runs/0.13/ml20m-ALS
    - runs/0.13/ml20m-ALS.json
    wdir: ../..
  ml20m-IALS:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml20m -o runs/0.13/ml20m-IALS
      -M runs/0.13/ml20m-IALS.json IALS
    deps:
    - data-split/ml20m
    outs:
    - runs/0.13/ml20m-IALS
    - runs/0.13/ml20m-IALS.json
    wdir: ../..
  ml20m-II:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml20m -o runs/0.13/ml20m-II
      -M runs/0.13/ml20m-II.json II
    deps:
    - data-split/ml20m
    outs:
    - runs/0.13/ml20m-II
    - runs/0.13/ml20m-II.json
    wdir: ../..
  ml20m-implicit:
    cmd: python envtool.py --run 0.13 run-algo.py --splits data-split/ml20m -o runs/0.13/ml20m-implicit
      -M runs/0.13/ml20m-implicit.json implicit
    deps:
    - data-split/ml20m
    outs:
    - runs/0.13/ml20m-implicit
    - runs/0.13/ml20m-implicit.json
    wdir: ../..
